root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  include_dir = ["cmd", "internal", "migrations"]
  exclude_dir = ["vendor", "tmp", "bin"]
  delay = 1000
  kill_delay = 500
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
