apiVersion: v1
kind: Namespace
metadata:
  name: guard
  labels:
    name: guard
    app.kubernetes.io/name: guard
    app.kubernetes.io/instance: guard
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: corvus-guard
    app.kubernetes.io/managed-by: kubectl
