{{- if and (hasKey .Values "env") (gt (len .Values.env) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guard.fullname" . }}-config
  labels:
    {{- include "guard.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
{{- end }}
