{{- if and (hasKey .Values "secretEnv") (gt (len .Values.secretEnv) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guard.fullname" . }}-secret
  labels:
    {{- include "guard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
{{- end }}
